### ISSUE TITLE
Task 1.1

### ISSUE THREAD

**Issue by 3oss2000** [ahmedelsafty70/Task_with_Open-CV#1] opened 2021-04-17 13:36 UTC
- Edit directory to be compatible on any device
  `img = cv2.imread("D:\\chair.jpg")`

**Comment by karimkohel** [comment] 2021-04-23 01:03
please close the issue if the problem is fixed @ahmedelsafty70

**Comment by ahmedelsafty70** [comment] 2021-04-23 01:48
Ok

**Closed as completed** 2021-04-23 01:53 UTC
